from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime
import os


def generate_report(frames, accidents, risk):
    # Create reports folder if not exists
    os.makedirs("backend/reports", exist_ok=True)

    file_path = "backend/reports/traffic_report.pdf"

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    y = height - 50

    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, y, "Smart City Traffic AI – Accident Report")

    y -= 40
    c.setFont("Helvetica", 12)
    c.drawString(50, y, f"Generated On: {datetime.now()}")

    y -= 30
    c.drawString(50, y, f"Frames Processed: {frames}")

    y -= 20
    c.drawString(50, y, f"Accidents Detected: {accidents}")

    y -= 20
    c.drawString(50, y, f"Risk Level: {risk}")

    y -= 40
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(
        50,
        y,
        "This report was automatically generated by Smart City Traffic AI."
    )

    c.save()
    return file_path
